<a href="https://colab.research.google.com/github/makman6666/Projekt_Zaliczenie/blob/master/zadanie6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:

# Artificial Neural Network

# Installing Theano
# pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
# pip install tensorflow

# Installing Keras
# pip install --upgrade keras

# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 6:13].values
y = dataset.iloc[:, 13].values

# Encoding categorical data
#from sklearn.preprocessing import LabelEncoder, OneHotEncoder
#labelencoder_X_1 = LabelEncoder()
#X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
#labelencoder_X_2 = LabelEncoder()
#X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
#cat_features = [1]
#onehotencoder = OneHotEncoder(handle_unknown='ignore')
#X = onehotencoder.fit_transform(X).toarray()
#X = X[:, 1:]
#print(X.shape)

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 7))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 5, epochs = 15)

# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)


Epoch 1/15
8000/8000 [==============================] - 6s 803us/step - loss: 0.4698 - accuracy: 0.7956
Epoch 2/15
8000/8000 [==============================] - 6s 780us/step - loss: 0.4270 - accuracy: 0.7962
Epoch 3/15
8000/8000 [==============================] - 6s 777us/step - loss: 0.4164 - accuracy: 0.8235
Epoch 4/15
8000/8000 [==============================] - 6s 784us/step - loss: 0.4048 - accuracy: 0.8257
Epoch 5/15
8000/8000 [==============================] - 6s 790us/step - loss: 0.3956 - accuracy: 0.8301
Epoch 6/15
8000/8000 [==============================] - 7s 847us/step - loss: 0.3900 - accuracy: 0.8403
Epoch 7/15
8000/8000 [==============================] - 6s 779us/step - loss: 0.3852 - accuracy: 0.8440
Epoch 8/15
8000/8000 [==============================] - 6s 777us/step - loss: 0.3813 - accuracy: 0.8444
Epoch 9/15
8000/8000 [==============================] - 6s 778us/step - loss: 0.3783 - accuracy: 0.8462
Epoch 10/15
8000/8000 [==============================] - 6s 783u

In [0]:
print(cm)

[[1528   67]
 [ 211  194]]


In [0]:
# Artificial Neural Network

# Installing Theano
# pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
# pip install tensorflow

# Installing Keras
# pip install --upgrade keras

# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('pima_indians_diabetes.txt')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, 8].values
print(dataset)
print(X)
print(y)
# Encoding categorical data
#from sklearn.preprocessing import LabelEncoder, OneHotEncoder
#labelencoder_X_1 = LabelEncoder()
#X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
#labelencoder_X_2 = LabelEncoder()
#X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
#onehotencoder = OneHotEncoder(categorical_features = [1])
#onehotencoder = OneHotEncoder(handle_unknown='ignore')
#X = onehotencoder.fit_transform(X).toarray()
#X = X[:, 3:]

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
print(X_train)
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 7))
# classifier.add(Dropout(p = 0.1))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
# classifier.add(Dropout(p = 0.1))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 25, epochs = 50)

# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Predicting a single new observation
"""Predict if the customer with the following informations will leave the bank:
Geography: France
Credit Score: 600
Gender: Male
Age: 40
Tenure: 3
Balance: 60000
Number of Products: 2
Has Credit Card: Yes
Is Active Member: Yes
Estimated Salary: 50000"""
#new_prediction = classifier.predict(sc.transform(np.array([[0.0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
#new_prediction = (new_prediction > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

# Part 4 - Evaluating, Improving and Tuning the ANN

# Evaluating the ANN
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 7))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 25, epochs = 50)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
print('mean przed optymalizacja')
print(mean)
print('variance przed optymalizacja')
variance = accuracies.std()
print(variance)
print('cm matrix przed optymalizacja')
print(cm)

# Improving the ANN
# Dropout Regularization to reduce overfitting if needed

# Tuning the ANN
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 7))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier)
parameters = {'batch_size': [25, 32],
              'epochs': [50, 75],
              'optimizer': ['adam', 'rmsprop']}
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10)
grid_search = grid_search.fit(X_train, y_train)
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

print('best_parameters',best_parameters)
print('best_accuracy',best_accuracy)

mean = accuracies.mean()
print('mean przed optymalizacja')
print(mean)
print('variance przed optymalizacja')
variance = accuracies.std()
print(variance)
print('cm matrix przed optymalizacja')
print(cm)

Streaming output truncated to the last 5000 lines.
Epoch 31/50
551/551 [==============================] - 0s 125us/step - loss: 0.4646 - accuracy: 0.7858
Epoch 32/50
551/551 [==============================] - 0s 124us/step - loss: 0.4643 - accuracy: 0.7840
Epoch 33/50
551/551 [==============================] - 0s 150us/step - loss: 0.4633 - accuracy: 0.7858
Epoch 34/50
551/551 [==============================] - 0s 119us/step - loss: 0.4628 - accuracy: 0.7840
Epoch 35/50
551/551 [==============================] - 0s 135us/step - loss: 0.4626 - accuracy: 0.7840
Epoch 36/50
551/551 [==============================] - 0s 127us/step - loss: 0.4624 - accuracy: 0.7858
Epoch 37/50
551/551 [==============================] - 0s 127us/step - loss: 0.4615 - accuracy: 0.7858
Epoch 38/50
551/551 [==============================] - 0s 127us/step - loss: 0.4616 - accuracy: 0.7877
Epoch 39/50
551/551 [==============================] - 0s 132us/step - loss: 0.4610 - accuracy: 0.7858
Epoch 40/50
551/551 [=

mean przed optymalizacja
0.7471972525119781
variance przed optymalizacja
0.04535365505756541
cm matrix przed optymalizacja
[[91 10]
 [21 32]]


 best_parameters {'batch_size': 25, 'epochs': 75, 'optimizer': 'rmsprop'}
best_accuracy 0.7749338974087784
mean po optymalizacja
0.7797461569309234
variance po optymalizacja
0.047699815573599834
cm matrix po optymalizacja
[[91 10]
 [22 31]]

In [0]:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import confusion_matrix
urlhd="http://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data"


nameshd = [
'age',
'sex',
'cp',
'trestbps',
'chol',
'fbs',
'restecg',
'thalach',
'exang',
'oldpeak',
'slope',
'ca',
'thal',
'num(the predicted attribute)']

datasethd = pd.read_csv(urlhd, names=nameshd)
df2=pd.DataFrame(data=datasethd,columns=nameshd,)
df2.index = [x for x in range(1, len(df2.values)+1)]
df2_dummies=pd.get_dummies(df2)


#print(df2_dummies.iloc[0])

# Importing the dataset
#dataset = pd.read_csv('pima_indians_diabetes.txt')
#X = df2_dummies.iloc[:, [0,1]].values
X = df2_dummies.iloc[:, [0,1,2,3,4,5,6,7,8,9,10,12,13,14,15,17,18,19]].values
y = df2_dummies.iloc[:, 11].values

# Encoding categorical data
#from sklearn.preprocessing import LabelEncoder, OneHotEncoder
#labelencoder_X_1 = LabelEncoder()
#X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
#labelencoder_X_2 = LabelEncoder()
#X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
#onehotencoder = OneHotEncoder(categorical_features = [1])
#onehotencoder = OneHotEncoder(handle_unknown='ignore')
#X = onehotencoder.fit_transform(X).toarray()
#X = X[:, 3:]

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 18))
# classifier.add(Dropout(p = 0.1))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
# classifier.add(Dropout(p = 0.1))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 25, epochs = 50)

#Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Predicting a single new observation
"""Predict if the customer with the following informations will leave the bank:
Geography: France
Credit Score: 600
Gender: Male
Age: 40
Tenure: 3
Balance: 60000
Number of Products: 2
Has Credit Card: Yes
Is Active Member: Yes
Estimated Salary: 50000"""
#new_prediction = classifier.predict(sc.transform(np.array([[0.0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
#new_prediction = (new_prediction > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
# Part 4 - Evaluating, Improving and Tuning the ANN

# Evaluating the ANN
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 18))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 25, epochs = 50)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
print('mean przed optymalizacja')
print(mean)
print('variance przed optymalizacja')
variance = accuracies.std()
print(variance)
print('cm matrix przed optymalizacja')
print(cm)


# Improving the ANN
# Dropout Regularization to reduce overfitting if needed
#classifier.add(Dropout(p = 0.1))
# Tuning the ANN
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 18))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier


classifier = KerasClassifier(build_fn = build_classifier)
parameters = {'batch_size': [25, 32],
              'epochs': [50, 75],
              'optimizer': ['adam', 'rmsprop']}
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10)
grid_search = grid_search.fit(X_train, y_train)
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

print('best_parameters',best_parameters)
print('best_accuracy',best_accuracy)

mean = accuracies.mean()
print('mean przed optymalizacja')
print(mean)
print('variance przed optymalizacja')
variance = accuracies.std()
print(variance)
print('cm matrix przed optymalizacja')
print(cm)

Streaming output truncated to the last 5000 lines.
217/217 [==============================] - 0s 126us/step - loss: 0.6624 - accuracy: 0.1613
Epoch 8/50
217/217 [==============================] - 0s 120us/step - loss: 0.6530 - accuracy: 0.1613
Epoch 9/50
217/217 [==============================] - 0s 126us/step - loss: 0.6409 - accuracy: 0.1613
Epoch 10/50
217/217 [==============================] - 0s 125us/step - loss: 0.6236 - accuracy: 0.1613
Epoch 11/50
217/217 [==============================] - 0s 129us/step - loss: 0.6050 - accuracy: 0.1613
Epoch 12/50
217/217 [==============================] - 0s 132us/step - loss: 0.5772 - accuracy: 0.1613
Epoch 13/50
217/217 [==============================] - 0s 139us/step - loss: 0.5479 - accuracy: 0.1613
Epoch 14/50
217/217 [==============================] - 0s 126us/step - loss: 0.5097 - accuracy: 0.1613
Epoch 15/50
217/217 [==============================] - 0s 131us/step - loss: 0.4656 - accuracy: 0.1613
Epoch 16/50
217/217 [===============

mean przed optymalizacja
0.4138333335518837
variance przed optymalizacja
0.12491119162863969
cm matrix przed optymalizacja
[[30  5  0  0  0]
 [ 6  7  0  0  0]
 [ 1  5  0  0  0]
 [ 0  4  0  0  0]
 [ 0  3  0  0  0]]
 
 best_parameters {'batch_size': 25, 'epochs': 50, 'optimizer': 'adam'}
best_accuracy 0.5331666666666666
mean po optymalizacja
0.4498333349823952
variance po optymalizacja
0.16993536538133866
cm matrix po optymalizacja
[[30  5  0  0  0]
 [ 6  7  0  0  0]
 [ 1  5  0  0  0]
 [ 0  4  0  0  0]
 [ 0  3  0  0  0]]